FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
	&& apt-get upgrade -y \
	&& apt-get install -yq \
	python3 curl wget gnupg \
	&& apt-get update -yq

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash \
	&& apt install -y nodejs

RUN apt-get install -y python3-pip \
	&& pip3 install --upgrade pip \
	&& pip3 install robotframework robotframework-browser pyyaml

RUN apt-get install -yq libglib2.0-0 \
	libnss3 \
    	libnspr4 \
    	libatk1.0-0 \
    	libatk-bridge2.0-0 \
    	libcups2 \
    	libdrm2 \
    	libdbus-1-3 \
    	libatspi2.0-0 \
    	libx11-6 \
    	libxcomposite1 \
    	libxdamage1 \
    	libxext6 \
    	libxfixes3 \
    	libxrandr2 \
    	libgbm1 \
    	libxcb1 \
    	libxkbcommon0 \
    	libpango-1.0-0 \
    	libcairo2 \
    	libasound2

RUN rfbrowser init


